//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KafeVTEntities1 : DbContext
    {
        public KafeVTEntities1()
            : base("name=KafeVTEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLAdmin> TBLAdmin { get; set; }
        public virtual DbSet<TBLAdres> TBLAdres { get; set; }
        public virtual DbSet<TBLBlog> TBLBlog { get; set; }
        public virtual DbSet<TBLHakkimizda> TBLHakkimizda { get; set; }
        public virtual DbSet<TBLiletisim> TBLiletisim { get; set; }
        public virtual DbSet<TBLKafe> TBLKafe { get; set; }
        public virtual DbSet<TBLSalon> TBLSalon { get; set; }
        public virtual DbSet<TBLSalonBlog> TBLSalonBlog { get; set; }
        public virtual DbSet<TBLSalonYorum> TBLSalonYorum { get; set; }
        public virtual DbSet<TBLYetenek> TBLYetenek { get; set; }
        public virtual DbSet<TBLYonetici> TBLYonetici { get; set; }
        public virtual DbSet<TBLYorum> TBLYorum { get; set; }
    }
}
