//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdres
    {
        public byte id { get; set; }
        public string Aciklama { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string AcikAdres { get; set; }
    }
}
