//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAdmin
    {
        public int id { get; set; }
        public string KullaniciAd { get; set; }
        public string Sifre { get; set; }
        public string Mail { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
