//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHakkimizda
    {
        public byte id { get; set; }
        public string Baslik { get; set; }
        public string KafeAciklama { get; set; }
        public string DugunAciklama { get; set; }
    }
}
