//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSalonYorum
    {
        public int id { get; set; }
        public string AdSoyad { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> SalonBlogid { get; set; }
    
        public virtual TBLSalonBlog TBLSalonBlog { get; set; }
    }
}
