//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokatRestoran.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLYetenek
    {
        public byte id { get; set; }
        public string YetenekAd { get; set; }
        public Nullable<byte> Derece { get; set; }
        public string Aciklama { get; set; }
    }
}
